Fix: 테스트유저데이터 영속화
영속화되지 않아서 org.hibernate.TransientObjectException 예외발생으로 테스트가 실패

org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'io.hhplus.concert.domain.user.User' (save the transient instance before flushing)

(cherry picked from commit 616e1f8c04a28fd54857e83d8ebe1b71e4b1c341)